<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CmsCore\Interfaces.csproj" />
    <ProjectReference Include="..\DbContext\DbContexts.csproj" />
    <ProjectReference Include="..\Models\CmsModels.csproj" />
  </ItemGroup>

</Project>
